version: '3.8'

services:
  currency_db:
    image: postgres:16.1
    container_name: currency_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: currency_db
    ports:
      - "5435:5432"
    networks:
      - currency_network

networks:
  currency_network:
    driver: bridge